function show(req, res, connection){
    res.statusCode = 404;
    let response = {"error": 404, "reason": "No video specified."};
    const videos = [{
        "id": 0, // Unique video ID - autogenerated
        "title": "String", // Video title
        "description": "Some full text description", // Video description
        "categories": [
            {
                "id": "string", // Unique category entity identifier - picked by user from list of existing categories
                "match": 0.8 // Float from 0.1 to 1.0 - How does the video match the category
            },
            {
                "id": "string", // Another category identifier
                "march": 0.2
            }
        ],
        "keywords": [
            "key1", // Single keyword
            "key2" // Another keyword
        ],
        "author": "String Stringson", // Author name
        "license": "Some license", // Video License
        "duration": 0, // Video duration
        "created": "2021-12-13", // Video creation date (by author)
        "added": "2023-03-02T12:12:34Z", // Entry creation date (by admin)
        "modified": "2023-03-03T10:01:50Z", // Modification date
        "link": "https://youtube.com/uri", // Link to actual video
        "mutation": {
            "dabing": [ // List of dabing mutations
                "en"
            ],
            "subtitles": [ // List of subs mutations
                "en",
                "cs",
                "de"
            ]
        }
    }];
    if (req.query.hasOwnProperty('id')) {
        if (req.query.id.length != 0) {
            response.reason = "No such video."
            videos.every((element) => {
                if (element.id == req.query.id) {
                    response = element; 
                    res.statusCode = 200;
                    return false;}
            });
        }
    }
    res.json(response);
};

module.exports = { show };